[package]
name = "foodfy-rust-api"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde = "1.0.203"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
tower = "0.4.13"
