services:
    api:
        build: .
        environment:
            PORT: 3333
        ports:
            - 3333:3333
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "256MB"
