services:
    app:
        build: .
        environment:
            PORT: 3333
        ports:
            - 3333:3333
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "256MB"

    postgres:
        image: bitnami/postgresql:16.3.0
        ports:
            - 5432:5432
        environment:
            POSTGRESQL_USERNAME: docker
            POSTGRESQL_PASSWORD: docker
            POSTGRESQL_DATABASE: foodfy
        volumes:
            - foodfy_db_data:/bitnami/postgresql
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1GB"

volumes:
    foodfy_db_data:
